// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbpHac7-VBqIQ5IwHwCc821C1go-y_PS0',
    appId: '1:731430801311:web:8369ea9d79e61e546477aa',
    messagingSenderId: '731430801311',
    projectId: 'aura-app-8a19f',
    authDomain: 'aura-app-8a19f.firebaseapp.com',
    storageBucket: 'aura-app-8a19f.appspot.com',
    measurementId: 'G-XV2LL2KV7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhkwELR9asHQ2xnzv3ArRiinABWbJG1Kg',
    appId: '1:731430801311:android:47662b2c29821da66477aa',
    messagingSenderId: '731430801311',
    projectId: 'aura-app-8a19f',
    storageBucket: 'aura-app-8a19f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGjq9qE8qqbDNBJJItKCPTOM6bCU6TxSs',
    appId: '1:731430801311:ios:bacb4bed28a6e5086477aa',
    messagingSenderId: '731430801311',
    projectId: 'aura-app-8a19f',
    storageBucket: 'aura-app-8a19f.appspot.com',
    iosClientId: '731430801311-gmtjuuahm4nfm20l3fj7b53a1a0n0ek2.apps.googleusercontent.com',
    iosBundleId: 'com.auraapp.app',
  );
}
